

spring:
  redis:
     host: 127.0.0.1  # Redis\u670D\u52A1\u5668\u5730\u5740
     port: 6379 # Redis\u670D\u52A1\u5668\u7AEF\u53E3\u53F7
     database: 0 # \u4F7F\u7528\u7684\u6570\u636E\u5E93\u7D22\u5F15\uFF0C\u9ED8\u8BA4\u662F0
     timeout: 1800000 # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
#\u6570\u636E\u6E90
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis\u914D\u7F6E
mybatis:
  type-aliases-package: com.lgx.springbootredis.pojo   #   \u522B\u540D
  mapper-locations: classpath:/mybatis/*.xml   #   xml\u6587\u4EF6
#\u65E5\u5FD7\u914D\u7F6E
logging:
  level:
    com:
      lgx: debug
  file:
    name: D:/logs/cont/aa.log



